-- BCBSA Plan Onboarding SQL
-- Generated: 2024-11-15 10:30:00
-- Total Statements: 8

-- ========== L4_GROUP_REFERENCE ==========
INSERT INTO L4_GROUP_REFERENCE (GROUP_ID, GROUP_NAME, GROUP_TYPE, EFFECTIVE_DATE, END_DATE, STATUS, CREATED_BY, CREATED_DATE) VALUES ('GRP001', 'Blue Shield California', 'LARGE_GROUP', '2024-11-01', NULL, 'ACTIVE', CURRENT_USER, CURRENT_TIMESTAMP);
INSERT INTO L4_GROUP_REFERENCE (GROUP_ID, GROUP_NAME, GROUP_TYPE, EFFECTIVE_DATE, END_DATE, STATUS, CREATED_BY, CREATED_DATE) VALUES ('GRP002', 'Anthem Blue Cross', 'LARGE_GROUP', '2024-11-01', NULL, 'ACTIVE', CURRENT_USER, CURRENT_TIMESTAMP);

-- ========== MI_ACCESS_CONTROL ==========
INSERT INTO MI_ACCESS_CONTROL (ACCESS_ID, USER_ID, ROLE_NAME, GROUP_ID, PERMISSION_LEVEL, GRANTED_DATE, EXPIRES_DATE) VALUES ('ACC001', 'U12345', 'ADMIN', 'GRP001', 'FULL', '2024-11-01', '2025-11-01');
INSERT INTO MI_ACCESS_CONTROL (ACCESS_ID, USER_ID, ROLE_NAME, GROUP_ID, PERMISSION_LEVEL, GRANTED_DATE, EXPIRES_DATE) VALUES ('ACC002', 'U12346', 'VIEWER', 'GRP001', 'READ', '2024-11-01', '2025-11-01');
INSERT INTO MI_ACCESS_CONTROL (ACCESS_ID, USER_ID, ROLE_NAME, GROUP_ID, PERMISSION_LEVEL, GRANTED_DATE, EXPIRES_DATE) VALUES ('ACC003', 'U12347', 'ADMIN', 'GRP002', 'FULL', '2024-11-01', '2025-11-01');
INSERT INTO MI_ACCESS_CONTROL (ACCESS_ID, USER_ID, ROLE_NAME, GROUP_ID, PERMISSION_LEVEL, GRANTED_DATE, EXPIRES_DATE) VALUES ('ACC004', 'U12348', 'EDITOR', 'GRP002', 'WRITE', '2024-11-01', '2025-11-01');

-- ========== SUBMISSION_GROUP_PLAN_REFERENCE ==========
INSERT INTO SUBMISSION_GROUP_PLAN_REFERENCE (PLAN_ID, PLAN_NAME, GROUP_ID, SUBMISSION_ID, PLAN_TYPE, NETWORK_TYPE, PREMIUM_AMOUNT, DEDUCTIBLE, OUT_OF_POCKET_MAX, COPAY_PRIMARY_CARE, COPAY_SPECIALIST, COPAY_ER, COPAY_URGENT_CARE, COINSURANCE, PRESCRIPTION_COVERAGE, DENTAL_INCLUDED, VISION_INCLUDED, MENTAL_HEALTH_COVERAGE, EFFECTIVE_DATE, END_DATE, STATUS, CREATED_BY, CREATED_DATE) VALUES ('PLN001', 'Blue Shield PPO Gold', 'GRP001', 'SUB2024110001', 'PPO', 'BROAD', 850.00, 1500, 6000, 25, 50, 300, 75, 0.20, 'YES', 'YES', 'YES', 'YES', '2024-11-01', NULL, 'ACTIVE', CURRENT_USER, CURRENT_TIMESTAMP);
INSERT INTO SUBMISSION_GROUP_PLAN_REFERENCE (PLAN_ID, PLAN_NAME, GROUP_ID, SUBMISSION_ID, PLAN_TYPE, NETWORK_TYPE, PREMIUM_AMOUNT, DEDUCTIBLE, OUT_OF_POCKET_MAX, COPAY_PRIMARY_CARE, COPAY_SPECIALIST, COPAY_ER, COPAY_URGENT_CARE, COINSURANCE, PRESCRIPTION_COVERAGE, DENTAL_INCLUDED, VISION_INCLUDED, MENTAL_HEALTH_COVERAGE, EFFECTIVE_DATE, END_DATE, STATUS, CREATED_BY, CREATED_DATE) VALUES ('PLN002', 'Anthem HMO Silver', 'GRP002', 'SUB2024110002', 'HMO', 'NARROW', 650.00, 2000, 7500, 20, 40, 250, 50, 0.30, 'YES', 'NO', 'YES', 'YES', '2024-11-01', NULL, 'ACTIVE', CURRENT_USER, CURRENT_TIMESTAMP);

-- ========== PLAN_REFERENCE ==========
INSERT INTO PLAN_REFERENCE (PLAN_ID, PLAN_CODE, PLAN_NAME, CARRIER_NAME, PLAN_YEAR, METAL_LEVEL, HSA_ELIGIBLE, FORMULARY_ID, NETWORK_ID, SERVICE_AREA, STATE, RATING_AREA, EFFECTIVE_DATE, END_DATE, STATUS, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES ('PLN001', 'BSC-PPO-G-2024', 'Blue Shield PPO Gold', 'Blue Shield of California', 2024, 'GOLD', 'NO', 'FORM001', 'NET001', 'CA-SF-BAY', 'CA', 'R001', '2024-11-01', '2024-12-31', 'ACTIVE', CURRENT_USER, CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO PLAN_REFERENCE (PLAN_ID, PLAN_CODE, PLAN_NAME, CARRIER_NAME, PLAN_YEAR, METAL_LEVEL, HSA_ELIGIBLE, FORMULARY_ID, NETWORK_ID, SERVICE_AREA, STATE, RATING_AREA, EFFECTIVE_DATE, END_DATE, STATUS, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES ('PLN002', 'ANT-HMO-S-2024', 'Anthem HMO Silver', 'Anthem Blue Cross', 2024, 'SILVER', 'YES', 'FORM002', 'NET002', 'CA-LA-METRO', 'CA', 'R002', '2024-11-01', '2024-12-31', 'ACTIVE', CURRENT_USER, CURRENT_TIMESTAMP, NULL, NULL);
