-- BCBSA Plan Onboarding SQL
-- Generated: 2026-02-20 17:19:35
-- Total Statements: 7


-- ========== L4_GROUP_REFERENCE ==========
INSERT INTO L4_GROUP_REFERENCE (L4_GRP_PLAN_ID_CD, NM, NOTIF_EMAIL_ADDR, EFF_DT, EXPRTN_DT, CRT_TS, CRT_USER_CD, UPDT_TS, UPDT_USER_CD) VALUES ('G01', 'National Health Insurance Trivandrum', 'Operationsteam@G01.com', '2008-01-01 00:00:00', '9999-12-31 00:00:00', NULL, NULL, NULL, NULL);

-- ========== MI_ACCESS_CONTROL ==========
INSERT INTO MI_ACCESS_CONTROL (BHI_HOME_PLAN_ID_CD, LOCN_CD, BHI_HOME_PLAN_NM, LOCN_NM, BHI_HLDNG_CMPNY_CD, BHI_HLDNG_CMPNY_NM, ANTHEM_PORTAL_IND) VALUES ('G15', 'bcbsa-chg', 'NHIT', 'Trivandrum', 'LH032', 'National Health Insurance Trivandrum', 'N');
INSERT INTO MI_ACCESS_CONTROL (BHI_HOME_PLAN_ID_CD, LOCN_CD, BHI_HOME_PLAN_NM, LOCN_NM, BHI_HLDNG_CMPNY_CD, BHI_HLDNG_CMPNY_NM, ANTHEM_PORTAL_IND) VALUES ('G15', 'bhi-chg', 'NHIT', 'Trivandrum', 'LH032', 'National Health Insurance Trivandrum', 'N');
INSERT INTO MI_ACCESS_CONTROL (BHI_HOME_PLAN_ID_CD, LOCN_CD, BHI_HOME_PLAN_NM, LOCN_NM, BHI_HLDNG_CMPNY_CD, BHI_HLDNG_CMPNY_NM, ANTHEM_PORTAL_IND) VALUES ('G15', 'bcbs-nc', 'National Health Insurance Trivandrum', 'Kochin', 'LH032', 'National Health Insurance Trivandrum', 'N');
INSERT INTO MI_ACCESS_CONTROL (BHI_HOME_PLAN_ID_CD, LOCN_CD, BHI_HOME_PLAN_NM, LOCN_NM, BHI_HLDNG_CMPNY_CD, BHI_HLDNG_CMPNY_NM, ANTHEM_PORTAL_IND) VALUES ('G15', 'nc-found', 'National Health Insurance Trivandrum', 'Kochin', 'LH032', 'National Health Insurance Trivandrum', 'N');

-- ========== SUBMISSION_GROUP_PLAN_REFERENCE ==========
INSERT INTO SUBMISSION_GROUP_PLAN_REFERENCE (SUBM_GRP_PLAN_ID_CD, SHRT_NM, LONG_NM, NOTIF_EMAIL_ADDR, XPCTD_SUBM_DAY, XPCTD_SUBM_BUS_DAY, INBND_CD_DRCTRY_FOLDER_NM, OTBND_CD_DRCTRY_FOLDER_NM, MED_DPLYMN_ANLYST_NOTIF_EMAIL_ADDR, PHRMCY_DPLYMN_ANLYST_NOTIF_EMAIL_ADDR, MED_DPLYMN_XPCTD_START_DT, PHRMCY_DPLYMN_XPCTD_START_DT, MED_PRDCTN_START_DT, PHRMCY_PRDCTN_START_DT, TEST_FILE_MAX_RECORD_CNT, PRDCTN_FILE_MAX_SUBM_CNT, CD_ZONE_ID_CD, EXTRCT_GRP_IND, EFF_DT, EXPRTN_DT, CRT_TS, CRT_USER_CD, UPDT_TS, UPDT_USER_CD, PROV_XWALK_IND, MEMB_REID_FILE_IND, BHI_IND, PI_INBND_CD_DRCTRY_FOLDER_NM, PI_OTBND_CD_DRCTRY_FOLDER_NM, PI_CD, PRDCTN_MEMB_MAX_SUBM_CNT, PRDCTN_ATRBTN_MAX_SUBM_CNT, MEMB_BNFT_FILE_IND, TOGETHER_GRP_IND) VALUES ('G01', 'NHIT', 'National Health Insurance Trivandrum', 'Operationsteam@G01.com', NULL, NULL, 'NDW/CDNC_zone/Plan_G01/Prod_Data', 'NDW/CDNC_zone/Plan_G01/Reports', 'NH_Processing_Notifications@Test.com', 'NH_Processing_Notifications@Test.com', '2025-01-01 00:00:00', '2025-01-01 00:00:00', '2025-04-01 00:00:00', '2025-04-02 00:00:00', 9999, 99, 'NC', 'P', '2008-01-01 00:00:00', '9999-12-31 00:00:00', NULL, NULL, NULL, NULL, 'Y', 'N', 'Y', 'NDW/CDNC_zone/Plan_G01/PI_Prod_Data​', 'NDW/CDNC_zone/Plan_G01/PI_Prod_Data/Reports/', 'Y', 3, 3, 'Y', 'S');

-- ========== PLAN_REFERENCE ==========
INSERT INTO PLAN_REFERENCE (BHI_HOME_PLAN_ID_CD, SUBM_GRP_PLAN_ID_CD, L4_GRP_PLAN_ID_CD, NOTIF_EMAIL_ADDR, OTBND_CD_DRCTRY_FOLDER_NM, PMO_REVW_IND, OWNING_PLAN_ID_CD, EFF_DT, EXPRTN_DT, CRT_TS, CRT_USER_CD, UPDT_TS, UPDT_USER_CD, PROV_MATCH_REJ_IND, BHI_IND, PI_OTBND_CD_DRCTRY_FOLDER_NM, HOST_GRP_PLAN_CD, HOME_GRP_PLAN_CD, PI_SPCL_PRCS_IND, MEMB_DEID_FILE_IND, DS_PROJ_NM, ANTHEM_SCHEMA_IND) VALUES ('G15', 'G01', 'G01', 'Operationsteam@G01.com', 'NDW/CDNC_zone/Plan_G01/Reports', 'N', 'G01', '2005-01-01 00:00:00', '9999-12-31 00:00:00', CURRENT_TIMESTAMP, CURRENT_USER, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
