-- BCBSA Plan Onboarding SQL
-- Generated: 2026-03-11 19:41:59
-- Total Statements: 2


-- ========== PLAN_REFERENCE ==========
INSERT INTO PLAN_REFERENCE (BHI_HOME_PLAN_ID_CD, SUBM_GRP_PLAN_ID_CD, L4_GRP_PLAN_ID_CD, NOTIF_EMAIL_ADDR, OTBND_CD_DRCTRY_FOLDER_NM, PMO_REVW_IND, OWNING_PLAN_ID_CD, EFF_DT, EXPRTN_DT, CRT_TS, CRT_USER_CD, UPDT_TS, UPDT_USER_CD, PROV_MATCH_REJ_IND, BHI_IND, PI_OTBND_CD_DRCTRY_FOLDER_NM, HOST_GRP_PLAN_CD, HOME_GRP_PLAN_CD, PI_SPCL_PRCS_IND, MEMB_DEID_FILE_IND, DS_PROJ_NM, ANTHEM_SCHEMA_IND) VALUES ('G15', 'G01', 'G01', 'nhi-kochin@bcbsa.com', 'NDW/CDNC_zone/Plan_G01/Reports', 'N', 'G01', '2025-02-01', '9999-12-31', CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, 'N', 'Y', 'NDW/CDNC_zone/Plan_G01/PI_Prod_Data/Reports/', 'G01', 'G15', 'N', 'N', 'NHI_Kochin_Onboard', 'N');
INSERT INTO PLAN_REFERENCE (BHI_HOME_PLAN_ID_CD, SUBM_GRP_PLAN_ID_CD, L4_GRP_PLAN_ID_CD, NOTIF_EMAIL_ADDR, OTBND_CD_DRCTRY_FOLDER_NM, PMO_REVW_IND, OWNING_PLAN_ID_CD, EFF_DT, EXPRTN_DT, CRT_TS, CRT_USER_CD, UPDT_TS, UPDT_USER_CD, PROV_MATCH_REJ_IND, BHI_IND, PI_OTBND_CD_DRCTRY_FOLDER_NM, HOST_GRP_PLAN_CD, HOME_GRP_PLAN_CD, PI_SPCL_PRCS_IND, MEMB_DEID_FILE_IND, DS_PROJ_NM, ANTHEM_SCHEMA_IND) VALUES ('H10', 'H05', 'H05', 'anthem-la@bcbsa.com', 'NDW/CDNC_zone/Plan_H05/Reports', 'Y', 'H05', '2025-02-01', '9999-12-31', CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, 'N', 'Y', 'NDW/CDNC_zone/Plan_H05/PI_Prod_Data/Reports/', 'H05', 'H10', 'N', 'Y', 'Anthem_CA_LA_Onboard', 'Y');
